creation_rules:
  - gcp_kms: projects/flask-sample-436101/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/mykey
    # Specify any file patterns you want to auto-encrypt
    path_regex: '.*\.yaml$'
    encrypted_regex: '^(data)$'