


apiVersion: v1
kind: ConfigMap
metadata:
  name: confnginx
data:
  nginx.conf:server {
  listen 83;
  location / {
    proxy_pass http://<your-upstream-url>:<upstream-port>;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Forwarded-Host $host;
  }
}